[package]
name = "merino-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.merino]
path = ".."

[[bin]]
name = "parse_greeting"
path = "fuzz_targets/parse_greeting.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse_userpass"
path = "fuzz_targets/parse_userpass.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse_request"
path = "fuzz_targets/parse_request.rs"
test = false
doc = false
bench = false

[[bin]]
name = "pretty_print_addr"
path = "fuzz_targets/pretty_print_addr.rs"
test = false
doc = false
bench = false
